import Foundation

enum ExerciseTypeResolverData {
    static let exactMatches: [String: ExerciseInputType] = [
        "treadmill": .distanceTime,
        "elliptical": .distanceTime,
        "elliptical trainer": .distanceTime,
        "cycling": .distanceTime,
        "spin bike": .distanceTime,
        "stationary bike": .distanceTime,
        "stationary cycle": .distanceTime,
        "assault bike": .distanceTime,
        "echo bike": .distanceTime,
        "air bike": .distanceTime,
        "ski erg": .distanceTime,
        "skierg": .distanceTime,
        "rowing machine": .distanceTime,
        "rower": .distanceTime,
        "sled push": .distanceTime,
        "sled pull": .distanceTime,
        "farmers walk": .distanceTime,
        "farmer's walk": .distanceTime,
        "farmer walk": .distanceTime,
        "farmer carry": .distanceTime,
        "loaded carry": .distanceTime,
        "running": .distanceTime,
        "running outdoor": .distanceTime,
        "jogging": .distanceTime,
        "sprinting": .distanceTime,
        "bike": .distanceTime,
        "run": .distanceTime,
        "swimming": .distanceOnly,
        "swim": .distanceOnly,
        "walking": .distanceOnly,
        "walk": .distanceOnly,
        "stair climber": .timeOnly,
        "stairmaster": .timeOnly,
        "stepmill": .timeOnly,
        "step mill": .timeOnly,
        "jump rope": .timeOnly,
        "battle rope": .timeOnly,
        "battle ropes": .timeOnly,
        "plank": .timeOnly,
        "wall sit": .timeOnly,
        "stretching": .timeOnly,
        "sauna": .timeOnly,
        "yoga": .repsOnly,
        "meditation": .timeOnly,
        "hollow hold": .timeOnly,
        "dead bug": .repsOnly,
        "sun salutation": .repsOnly,
        "vinyasa flow": .repsOnly,
        "vinyasa": .repsOnly,
        "yin yoga": .timeOnly,
        "power yoga": .repsOnly,
        "warrior i": .repsOnly,
        "warrior ii": .repsOnly,
        "warrior iii": .repsOnly,
        "warrior 1": .repsOnly,
        "warrior 2": .repsOnly,
        "warrior 3": .repsOnly,
        "triangle pose": .repsOnly,
        "tree pose": .repsOnly,
        "chair pose": .repsOnly,
        "mountain pose": .repsOnly,
        "eagle pose": .repsOnly,
        "downward dog": .repsOnly,
        "upward dog": .repsOnly,
        "cobra pose": .repsOnly,
        "camel pose": .repsOnly,
        "wheel pose": .repsOnly,
        "bridge pose": .repsOnly,
        "bow pose": .repsOnly,
        "pigeon pose": .timeOnly,
        "seated forward fold": .timeOnly,
        "butterfly stretch": .timeOnly,
        "supine twist": .repsOnly,
        "child's pose": .timeOnly,
        "childs pose": .timeOnly,
        "happy baby": .repsOnly,
        "legs up the wall": .timeOnly,
        "corpse pose": .timeOnly,
        "savasana": .timeOnly,
        "cat cow": .repsOnly,
        "cat-cow": .repsOnly,
        "hip flexor stretch": .timeOnly,
        "hamstring stretch": .timeOnly,
        "quad stretch": .timeOnly,
        "chest opener": .timeOnly,
        "shoulder stretch": .timeOnly,
        "thoracic rotation": .timeOnly,
        "world's greatest stretch": .timeOnly,
        "foam rolling": .timeOnly,
        "foam roll": .timeOnly,
        "pull-ups": .repsOnly,
        "pullups": .repsOnly,
        "pull ups": .repsOnly,
        "chin-ups": .repsOnly,
        "chinups": .repsOnly,
        "chin ups": .repsOnly,
        "push-ups": .repsOnly,
        "pushups": .repsOnly,
        "push ups": .repsOnly,
        "wall push-up": .repsOnly,
        "wall push up": .repsOnly,
        "wall pushup": .repsOnly,
        "kneeling push-up": .repsOnly,
        "kneeling pushup": .repsOnly,
        "handstand push-up": .repsOnly,
        "handstand pushup": .repsOnly,
        "handstand push ups": .repsOnly,
        "muscle-up": .repsOnly,
        "muscle up": .repsOnly,
        "muscle ups": .repsOnly,
        "kipping pull-up": .repsOnly,
        "kipping pullup": .repsOnly,
        "typewriter pull-up": .repsOnly,
        "dips": .repsOnly,
        "chest dips": .repsOnly,
        "jump squat": .repsOnly,
        "squat jump": .repsOnly,
        "squat jumps": .repsOnly,
        "air squat": .repsOnly,
        "air squats": .repsOnly,
        "bodyweight squat": .repsOnly,
        "bodyweight squats": .repsOnly,
        "pistol squat": .repsOnly,
        "pistol squats": .repsOnly,
        "single leg squat": .repsOnly,
        "single-leg squat": .repsOnly,
        "jump lunge": .repsOnly,
        "jump lunges": .repsOnly,
        "jumping lunge": .repsOnly,
        "jumping lunges": .repsOnly,
        "bodyweight lunge": .repsOnly,
        "bodyweight lunges": .repsOnly,
        "high knees": .repsOnly,
        "high knee": .repsOnly,
        "skater jump": .repsOnly,
        "skater jumps": .repsOnly,
        "lateral jump": .repsOnly,
        "lateral jumps": .repsOnly,
        "broad jump": .repsOnly,
        "broad jumps": .repsOnly,
        "tuck jump": .repsOnly,
        "tuck jumps": .repsOnly,
        "star jump": .repsOnly,
        "star jumps": .repsOnly,
        "bodyweight hip thrust": .repsOnly,
        "bodyweight glute bridge": .repsOnly,
        "crunch": .repsOnly,
        "crunches": .repsOnly,
        "leg raise": .repsOnly,
        "leg raises": .repsOnly,
        "hanging leg raise": .repsOnly,
        "hanging leg raises": .repsOnly,
        "hanging knee raise": .repsOnly,
        "hanging knee raises": .repsOnly,
        "toes to bar": .repsOnly,
        "toes-to-bar": .repsOnly,
        "t2b": .repsOnly,
        "knees to chest": .repsOnly,
        "v-up": .repsOnly,
        "v up": .repsOnly,
        "v-ups": .repsOnly,
        "v ups": .repsOnly,
        "dragon flag": .repsOnly,
        "dragon flags": .repsOnly,
        "ab wheel rollout": .repsOnly,
        "ab wheel": .repsOnly,
        "russian twist": .repsOnly,
        "russian twists": .repsOnly,
        "sit-up": .repsOnly,
        "sit-ups": .repsOnly,
        "sit up": .repsOnly,
        "sit ups": .repsOnly,
        "bicycle crunch": .repsOnly,
        "bicycle crunches": .repsOnly,
        "mountain climbers": .repsOnly,
        "mountain climber": .repsOnly,
        "burpee": .repsOnly,
        "burpees": .repsOnly,
        "jumping jack": .repsOnly,
        "jumping jacks": .repsOnly,
        "nordic hamstring curl": .repsOnly,
        "nordic curl": .repsOnly,
        "nordic curls": .repsOnly,
        "glute kickback": .repsOnly,
        "donkey kick": .repsOnly,
        "donkey kicks": .repsOnly,
        "fire hydrant": .repsOnly,
        "fire hydrants": .repsOnly,
        "side lying leg raise": .repsOnly,
        "hip raise": .repsOnly,
        "hip raises": .repsOnly,
        "box jump": .heightReps,
        "box jumps": .heightReps,
        "glute bridge": .repsOnly,
        "single leg hip thrust": .repsOnly,
        "clamshell": .repsOnly,
        "clamshells": .repsOnly,
        "side lying hip abduction": .repsOnly,
        "hip abduction (lying)": .repsOnly,
        "sissy squat": .repsOnly,
        "reverse nordic": .repsOnly,
        "terminal knee extension": .repsOnly,
        "tke": .repsOnly,
        "ankle circles": .repsOnly,
        "ankle dorsiflexion": .repsOnly,
        "tibialis raise": .repsOnly,
        "hip circle": .repsOnly,
        "ghd sit-up": .repsOnly,
        "oblique knee raise": .repsOnly,
        "captain's chair leg raise": .repsOnly,
        "decline sit-up": .repsOnly,
        "decline oblique crunch": .repsOnly,
        "leg raise on decline": .repsOnly,
        "oblique crunch": .repsOnly,
        "side plank": .timeOnly,
        "copenhagen plank": .timeOnly,
        "l-sit": .timeOnly,
        "l sit": .timeOnly,
        "bird dog": .repsOnly,
        "reverse crunch": .repsOnly,
        "reverse crunches": .repsOnly,
        "decline crunch": .repsOnly,
        "decline crunches": .repsOnly,
        "band pull apart": .repsOnly,
        "band pull aparts": .repsOnly,
        "pike push-up": .repsOnly,
        "pike push ups": .repsOnly,
        "pike pushup": .repsOnly,
        "inverted row": .repsOnly,
        "inverted rows": .repsOnly,
        "neutral grip pull-up": .repsOnly,
        "neutral grip pullup": .repsOnly,
        "assisted pull-up": .repsOnly,
        "assisted chin-up": .repsOnly,
        "wide grip pull-up": .repsOnly,
        "close grip chin-up": .repsOnly,
        "tricep dips": .repsOnly,
        "assisted tricep dip": .repsOnly,
        "close grip dip": .repsOnly,
        "ankle dorsiflexion stretch": .timeOnly,
        "calf stretch": .timeOnly,
        "90/90 hip stretch": .timeOnly,
        "couch stretch": .timeOnly,
        "figure 4 stretch": .timeOnly,
        "thoracic extension": .timeOnly,
        "thread the needle": .timeOnly,
        "band distraction hip": .timeOnly,
        "lacrosse ball massage": .timeOnly,
        "lateral lunge stretch": .timeOnly,
        "doorway chest stretch": .timeOnly,
        "neck rolls": .repsOnly,
        "shoulder circles": .repsOnly,
        "wrist circles": .repsOnly,
        "skipping": .timeOnly,
        "boxing": .timeOnly,
        "shadow boxing": .timeOnly,
        "hiit": .timeOnly,
        "sprint intervals": .timeOnly,
        "tabata protocol": .timeOnly,
        "steady climb": .timeOnly,
        "interval climb": .timeOnly,
        "stair sprint": .timeOnly,
        "side step climb": .timeOnly,
        "hill climb": .distanceTime,
        "incline walk": .distanceTime,
        "forward elliptical": .distanceTime,
        "reverse elliptical": .distanceTime,
        "incline elliptical": .distanceTime,
        "high resistance elliptical": .distanceTime,
        "steady state cycling": .distanceTime,
        "interval cycling": .distanceTime,
        "high resistance cycling": .distanceTime,
        "sprint cycling": .distanceTime,
        "endurance cycling": .distanceTime,
        "rowing": .distanceTime,
        "endurance row": .distanceTime,
        "sprint row intervals": .distanceTime,
        "power strokes": .distanceTime,
        "arm cycling": .distanceTime,
        "forward arm cycle": .distanceTime,
        "reverse arm cycle": .distanceTime,
        "interval arm cycling": .timeOnly,
        "wrist curl": .weightReps,
        "reverse wrist curl": .weightReps,
        "wrist roller": .repsOnly,
        "plate pinch": .timeOnly,
        "finger curls": .weightReps,
        "wrist extension": .weightReps,
        "grip training": .timeOnly,
        "farmers carry": .distanceOnly,
        "walking lunge": .weightReps,
        "walking lunges": .weightReps,
        "reverse lunge": .weightReps,
        "dumbbell walking lunge": .weightReps,
        "step up": .weightReps,
        "step ups": .weightReps,
        "vmo squat": .weightReps,
        "goblet squat": .weightReps,
        "split squat": .weightReps,
    ]

    // Order matters: first matching group wins, matching TYPE_PATTERNS's array order.
    static let patternGroups: [(patterns: [NSRegularExpression], type: ExerciseInputType)] = {
        func rx(_ pattern: String) -> NSRegularExpression {
            try! NSRegularExpression(pattern: pattern, options: [.caseInsensitive])
        }
        return [
            (patterns: [rx(#"\btreadmill\b"#), rx(#"\brilliant?ical\b"#), rx(#"\bski[\s-]?erg\b"#), rx(#"\bassault[\s-]bike\b"#), rx(#"\becho[\s-]bike\b"#), rx(#"\bair[\s-]bike\b"#), rx(#"\bspin[\s-]bike\b"#), rx(#"\bstationary[\s-](bike|cycle)\b"#), rx(#"sled[\s-]push"#), rx(#"sled[\s-]pull"#), rx(#"farmers?[\s-]walk"#), rx(#"farmer[\s-]carry"#), rx(#"loaded[\s-]carry"#), rx(#"\browing[\s-]machine\b"#), rx(#"\b(erg|rower)\b"#), rx(#"\brun(s|ning|ner)?\b"#), rx(#"\bjog(s|ging)?\b"#), rx(#"\bsprint(s|ing|er)?\b"#), rx(#"\bcycl(e|es|ing|ist)\b"#), rx(#"\bbike\b"#)], type: .distanceTime),
            (patterns: [rx(#"\bswim(s|ming|mer)?\b"#), rx(#"\bwalking\b(?!\s+lunge)"#), rx(#"\bwalk\b(?!\s+out|ing\s+lunge)"#)], type: .distanceOnly),
            (patterns: [rx(#"stair[\s-]?(master|climber|stepper)"#), rx(#"\bstepmill\b"#), rx(#"battle[\s-]ropes?"#), rx(#"\bjump[\s-]rope\b"#), rx(#"\bplank\b"#), rx(#"\bwall[\s-]sit\b"#), rx(#"\bsauna\b"#), rx(#"\bstretching?\b"#), rx(#"\bstretch(ing)?\b"#), rx(#"\bmeditation\b"#), rx(#"\bhollow[\s-]hold\b"#), rx(#"\bisometric\b"#), rx(#"\bfoam[\s-]roll(ing)?\b"#), rx(#"\bmobility\b"#), rx(#"\bsavasana\b"#)], type: .timeOnly),
            (patterns: [rx(#"\byoga\b"#), rx(#"\bvinyasa\b"#), rx(#"\basana\b"#), rx(#"\bpose\b"#), rx(#"\bwarrior\b"#), rx(#"\bpigeon\b"#), rx(#"\bnamaste\b"#), rx(#"\bpranayama\b"#), rx(#"\bcat[\s-]cow\b"#)], type: .repsOnly),
            (patterns: [rx(#"\bbodyweight\b"#), rx(#"\bair[\s-]squat\b"#), rx(#"\bpistol[\s-]squat\b"#), rx(#"\bhigh[\s-]knees?\b"#), rx(#"\bjump[\s-]lunge\b"#), rx(#"\bjumping[\s-]lunge\b"#), rx(#"\bskater[\s-]jump\b"#), rx(#"\btuck[\s-]jump\b"#), rx(#"\bstar[\s-]jump\b"#), rx(#"\bbroad[\s-]jump\b"#), rx(#"\bhandstand[\s-]push[\s-]?ups?\b"#), rx(#"\bmuscle[\s-]?ups?\b"#), rx(#"\bpull[\s-]?ups?\b"#), rx(#"\bchin[\s-]?ups?\b"#), rx(#"\bpush[\s-]?ups?\b"#), rx(#"\bdips?\b"#), rx(#"\bjump[\s-]squat\b"#), rx(#"\bdip\b"#), rx(#"\bcrunche?s?\b"#), rx(#"\bleg[\s-]raises?\b"#), rx(#"\bhanging[\s-](leg|knee)[\s-]raises?\b"#), rx(#"\btoes[\s-]to[\s-]bar\b"#), rx(#"\bt2b\b"#), rx(#"\bknees[\s-]to[\s-](chest|elbow)\b"#), rx(#"\bv[\s-]ups?\b"#), rx(#"\bdragon[\s-]flags?\b"#), rx(#"\bab[\s-]wheel\b"#), rx(#"\brussian[\s-]twists?\b"#), rx(#"\bsit[\s-]?ups?\b"#), rx(#"\bbicycle[\s-]crunche?s?\b"#), rx(#"\bmountain[\s-]climbers?\b"#), rx(#"\bburpees?\b"#), rx(#"\bjumping[\s-]jacks?\b"#), rx(#"\bnordic[\s-](hamstring[\s-])?curls?\b"#), rx(#"\bglute[\s-]kickbacks?\b"#), rx(#"\bdonkey[\s-]kicks?\b"#), rx(#"\bfire[\s-]hydrants?\b"#), rx(#"\bhip[\s-]raises?\b"#)], type: .repsOnly),
            (patterns: [rx(#"\bbox[\s-]jumps?\b"#), rx(#"\bdepth[\s-]jumps?\b"#)], type: .heightReps),
        ]
    }()
}
